CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tg_user_id BIGINT NOT NULL UNIQUE,
    tg_username TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_settings (
    user_id BIGINT NOT NULL PRIMARY KEY REFERENCES users(id),
    timezone TEXT NOT NULL
);

CREATE TABLE inbox_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    content TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_inbox_item_status
        CHECK (status IN ('ACTIVE', 'PROCESSED', 'ARCHIVED'))
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    inbox_item_id BIGINT REFERENCES inbox_items(id),
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    CONSTRAINT chk_task_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),

    CONSTRAINT chk_task_status
        CHECK (status IN ('OPEN', 'COMPLETED')),

    CONSTRAINT chk_task_completion
        CHECK (
            (status = 'OPEN' AND completed_at IS NULL)
            OR
            (status = 'COMPLETED' AND completed_at IS NOT NULL)
        )
);

CREATE TABLE notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    inbox_item_id BIGINT REFERENCES inbox_items(id),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE note_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    tag TEXT NOT NULL,

    CONSTRAINT uq_note_tags_user_tag
        UNIQUE (user_id, tag)
);

CREATE TABLE note_to_tag (
    note_id BIGINT NOT NULL REFERENCES notes(id),
    tag_id BIGINT NOT NULL REFERENCES note_tags(id),

    PRIMARY KEY (note_id, tag_id)
);
